### ISSUE TITLE
Many types of geometries fail with intersects filter and POST

### ISSUE THREAD

**Issue by philvarner** [nasa/cmr-stac#188]
Running against https://cmr.earthdata.nasa.gov/stac/LARC_ASDC

These queries fail:

- POST Search with intersects:{'type': 'LineString', 'coordinates': [[100.0, 0.0], [101.0, 1.0]]} returned status code 400
- POST Search with intersects:{'type': 'Polygon', 'coordinates': [[[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]]]} returned status code 502
- POST Search with intersects:{'type': 'Polygon', 'coordinates': [[[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]], [[100.8, 0.8], [100.8, 0.2], [100.2, 0.2], [100.2, 0.8], [100.8, 0.8]]]} returned status code 502
- POST Search with intersects:{'type': 'MultiPoint', 'coordinates': [[100.0, 0.0], [101.0, 1.0]]} returned status code 400
- POST Search with intersects:{'type': 'MultiLineString', 'coordinates': [[[100.0, 0.0], [101.0, 1.0]], [[102.0, 2.0], [103.0, 3.0]]]} returned status code 400
- POST Search with intersects:{'type': 'MultiPolygon', 'coordinates': [[[[102.0, 2.0], [103.0, 2.0], [103.0, 3.0], [102.0, 3.0], [102.0, 2.0]]], [[[100.0, 0.0], [101.0, 0.0], [101.0, 1.0], [100.0, 1.0], [100.0, 0.0]], [[100.2, 0.2], [100.2, 0.8], [100.8, 0.8], [100.8, 0.2], [100.2, 0.2]]]]} returned status code 502

oddly, Point and GeometryCollection both work.

**Comment by matthewhanson** [comment]
@philvarner Thanks for this, I went to replicate the issues here. I thought it odd Polygon didn't work, since I've used that a bunch.  
I found out there is something that is causing the LARC_ASDC provider data to be really really slow when searching CMR.

The LARC_ASDC provider has about 5.5 million granules, and this CMR call:
```
time curl "https://cmr.earthdata.nasa.gov/search/granules.umm_json?provider=LARC_ASDC&page_size=0&polygon=100,0,101,0,101,1,100,1,100,0"
```
takes 25 seconds

But doing an identical search to USGS_EROS, which has 11 million granules:
```
time curl "https://cmr.earthdata.nasa.gov/search/granules.umm_json?provider=USGS_EROS&page_size=0&polygon=100,0,101,0,101,1,100,1,100,0"
```
takes less than a second

So there appears to be 2 different issues here, one is the LARC_ASDC slowness which is a CMR issue.  For now it probably doesn't make sense to test using that provider endpoint (I wonder if there are other providers that have the same problem).

I'm testing out the other geometry cases, it seems they are not being handled correctly and it tries to turn all coordinates into polygon CMR queries.

**Comment by philvarner** [comment]
Ah, I'll start using USGS_EROS for testing, and watch out for the 502s. 

With that, I only get these failing:

```
- POST Search with intersects:{'type': 'LineString', 'coordinates': [[100.0, 0.0], [101.0, 1.0]]} returned status code 400
- POST Search with intersects:{'type': 'MultiPoint', 'coordinates': [[100.0, 0.0], [101.0, 1.0]]} returned status code 400
- POST Search with intersects:{'type': 'MultiLineString', 'coordinates': [[[100.0, 0.0], [101.0, 1.0]], [[102.0, 2.0], [103.0, 3.0]]]} returned status code 400
```

**Comment by matthewhanson** [comment]
The MultiPolygon and Point actually shouldn't have worked either, or at least they would have given incorrect results.

All geometry types are supported now, should be on production in a few weeks.

Polygons will Linear rings will throw an error
