### ISSUE TITLE
Need better Item IDs

### ISSUE THREAD

**Issue by matthewhanson** [nasa/cmr-stac#21]
Similar to #20, Items also seem to be using the same generic IDs, probably from CMR.

The Item IDs are less important than for collections, but these are clearly different than the 'Granule ID' that is normally used.   The granule ID is what should be the STAC Item id.

**Comment by scottyhq** [comment]
@matthewhanson I'd like to second this. Here is a concrete example with the current `"stac_version": "1.0.0-rc.4",` I think it's quite common to know a Granule ID, but not an internal CMR ID, which seems to be used currently

For example, consider this Granule ID to STAC Item ID mapping:
`S1A_IW_GRDH_1SDV_20170101T021007_20170101T021036_014632_017CAA_D7AD --> G1360802832-ASF`

The only way I've managed to figure out that mapping is to go to [Earthdata search and look at the 'information' tab](https://search.earthdata.nasa.gov/search/granules/granule-details?p=C1214470533-ASF&pg[0][id]=S1A_IW_GRDH_1SDV_20170101T021007_20170101T021036_014632_017CAA_D7AD&pg[0][gsk]=-start_date&g=G1360802832-ASF&q=SENTINEL-1A_DP_GRD_HIGH&tl=1623097752!3!!&m=0!0.140625!2!1!0!0%2C2): 

I think for user friendliness and for the sake of interoperability it makes sense to use the producerGranuleId? That way we could access the STAC record at:

https://cmr.earthdata.nasa.gov/stac/ASF/collections/SENTINEL-1A_DP_GRD_HIGH.v1/items/S1A_IW_GRDH_1SDV_20170101T021007_20170101T021036_014632_017CAA_D7AD

instead of
https://cmr.earthdata.nasa.gov/stac/ASF/collections/SENTINEL-1A_DP_GRD_HIGH.v1/items/G1360802832-ASF
