### ISSUE TITLE
Collection names have changed for LP Cloud?

### ISSUE THREAD

**Issue by scottyhq** [nasa/cmr-stac#277]
Last week this was a valid item URL: `https://cmr.earthdata.nasa.gov/cloudstac/LPCLOUD/collections/HLSS30.v2.0/items/HLS.S30.T13SDV.2022001T175739.v2.0`

It now returns:
```
{
  "status": 503,
  "errors": [
    "Oops! A problem occurred upstream and we were unable to process your request. We have been alerted and are working to resolve the problem. Please try your request again later."
  ]
}
```

I see here https://cmr.earthdata.nasa.gov/cloudstac/LPCLOUD lots of "collectionConceptId" which I thought were done away with for more intuitive user-facing names?
```
{"rel":"child","href":"https://cmr.earthdata.nasa.gov/cloudstac/LPCLOUD/collections/C2021957657-LPCLOUD","type":"application/json"},{"rel":"child","href":"https://cmr.earthdata.nasa.gov/cloudstac/LPCLOUD/collections/C2021957295-LPCLOUD","type":"application/json"},{"rel":"child","href":"https://cmr.earthdata.nasa.gov/cloudstac/LPCLOUD/collections/C1711961296-LPCLOUD","type":"application/json"},{"rel":"child","href":"https://cmr.earthdata.nasa.gov/cloudstac/LPCLOUD/collections/C1748066515-LPCLOUD","type":"application/json"},{"rel":"child","href":"https://cmr.earthdata.nasa.gov/cloudstac/LPCLOUD/collections/C2218777082-LPCLOUD","type":"application/json"},{"rel":"child","href":"https://cmr.earthdata.nasa.gov/cloudstac/LPCLOUD/collections/C2202497474-LPCLOUD","type":"application/json"},
```

Looking at https://cmr.earthdata.nasa.gov/cloudstac/LPCLOUD/collections/C2021957295-LPCLOUD shows 
"HLS Sentinel-2 Multi-spectral Instrument Surface Reflectance Daily Global 30m v2.0"

But https://cmr.earthdata.nasa.gov/cloudstac/LPCLOUD/collections/C2021957295-LPCLOUD/items returns items seemingly from *all* collections including MODIS:
```
  "stac_version": "1.0.0",
  "numberMatched": 66094711,
  "numberReturned": 20,
  "features": [
    {
      "type": "Feature",
      "id": "G2330080324-LPCLOUD",
```

Not sure what has happened behind the scenes between last week and today, but these are pretty significant breakages / changes in behavior...

**Comment by william-valencia** [comment]
Hi Scott,

Looks like your original link works.
https://cmr.earthdata.nasa.gov/cloudstac/LPCLOUD/collections/HLSS30.v2.0/items/HLS.S30.T13SDV.2022001T175739.v2.0

When the updated version of CMR-STAC gets deployed to cloudstac, the collection name will change slightly. It will be HLSS30_2.0 instead of HLSS30.v2.0. So the link will be
https://cmr.earthdata.nasa.gov/cloudstac/LPCLOUD/collections/HLSS30_2.0/items/HLS.S30.T13SDV.2022001T175739.v2.0

You can test this out now here in:
https://cmr.earthdata.nasa.gov/stac/LPCLOUD/collections/HLSS30_2.0/items/HLS.S30.T13SDV.2022001T175739.v2.0
