### ISSUE TITLE
Question about asset identifiers

### ISSUE THREAD

**Issue by abarciauskas-bgse** [nasa/cmr-stac#326]
We are doing a little project that uses the STAC render extension to visualize NASA data via it's representation in CMR. We noticed that there is no way to associate data URLs with specific asset names (like band names) in CMR's UMM model but that in cmr-stac asset keys are present. We noticed that in cmr-stac there is an assumption that the asset identifier is always the second to last string in a URL ([code here](https://github.com/nasa/cmr-stac/blob/master/src/utils/index.ts#L45-L53)). We are curious if this is a safe assumption to make for our use case as well - in other words - how many collections in CMR adhere to this URL scheme?

**Comment by william-valencia** [comment]
Drew Pesall responded:

The answer to your question is a bit complicated, because not all collections adhere to this schema. I can't really estimate how many collections adhere to this schema, so for some collections with relatedUrls it looks a bit goofy because the selected string to be used as the key is not particularly informative, but it still generates the key either way.

so I think this method sounds pretty unreliable.
